# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agent < Formula
  desc "Semaphore 2.0 agent."
  homepage "https://semaphoreci.com"
  version "2.2.14"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/semaphoreci/agent/releases/download/v2.2.14/agent_Darwin_x86_64.tar.gz"
      sha256 "2bceb21452ecb014c1cef5f5595d585a3be9496ad096a9fa563d322eb404fb98"

      def install
        bin.install "agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/semaphoreci/agent/releases/download/v2.2.14/agent_Darwin_arm64.tar.gz"
      sha256 "713006b21fbadc48ae42477057cc6935669caedd73ca69677c815471e405dc4d"

      def install
        bin.install "agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/semaphoreci/agent/releases/download/v2.2.14/agent_Linux_armv6.tar.gz"
      sha256 "73d28fd0550447d5bd7e6007f30e95b538336c8992b957e7739c8a424152c078"

      def install
        bin.install "agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/semaphoreci/agent/releases/download/v2.2.14/agent_Linux_arm64.tar.gz"
      sha256 "f708f203e0c2a8abc21a90f0158842f6f4e2772704732683b1310499dfb39a0a"

      def install
        bin.install "agent"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/semaphoreci/agent/releases/download/v2.2.14/agent_Linux_x86_64.tar.gz"
      sha256 "97e0b7436f134295c30f795f1db0914aecf0bd2b6806b5e95781425b2c7ff7fb"

      def install
        bin.install "agent"
      end
    end
  end

  test do
    system "#{bin}/agent version"
  end
end
