# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sem < Formula
  desc "Semaphore 2.0 command line interface."
  homepage "https://semaphoreci.com"
  version "0.33.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/semaphoreci/cli/releases/download/v0.33.1/sem_Darwin_x86_64.tar.gz"
      sha256 "5ca22bb7dfc73e0ea2fd57549a27c3230b2e96dcc3a99f655cac4fc7e6f77ea2"

      def install
        bin.install "sem"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/semaphoreci/cli/releases/download/v0.33.1/sem_Darwin_arm64.tar.gz"
      sha256 "206e0729c34989e7afe0b89cc69bc0615ac63ae43201dc6f9149c58305a8d790"

      def install
        bin.install "sem"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/semaphoreci/cli/releases/download/v0.33.1/sem_Linux_x86_64.tar.gz"
      sha256 "aef91c51521ce44b1f812201b463ec1b1391aa23c455f28faedf04e237c37176"

      def install
        bin.install "sem"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/semaphoreci/cli/releases/download/v0.33.1/sem_Linux_arm64.tar.gz"
      sha256 "3c6082b32326f42c9c3ed4afe80a7728e765758fd0ff93e95a2186edb6a53a4d"

      def install
        bin.install "sem"
      end
    end
  end

  test do
    system "#{bin}/sem version"
  end
end
